version: 2.1
workflows:
  build-and-test:
    jobs:
      - build-and-test

orbs:
  node: circleci/node@2.1.1

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

